name: Tests

on: [push]

jobs:
  cs-check:
    name: Check Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache composer
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/
          key: composer-ubuntu-${{ github.sha }}

      - name: Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, fileinfo, json, intl, dom
          tools: castor

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Install qa tooling
        run: castor qa:update

      - name: Check coding standards
        run: castor qa:cs --dry-run

  tests:
    name: Run tests for PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        php-versions:  ['8.1', '8.2', '8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache composer
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/
          key: composer-${{ matrix.php-versions }}-${{ github.sha }}

      - name: setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, fileinfo, json, intl, dom
          tools: castor

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run tests
        run: castor qa:test
